// ========== CUSTOMER CLASS ==========
class Customer {
    constructor(name, phone) {
        this.id = null; // Will be generated by DatabaseManager
        this.name = name || '';
        this.phone = phone || '';
        this.notes = '';
        this.measurements = this.createEmptyMeasurements();
        this.models = {
            yakhun: '',
            sleeve: '',
            skirt: [],
            features: []
        };
        this.sewingPriceAfghani = null;
        this.deliveryDay = '';
        this.paymentReceived = false;
        this.paymentDate = null;
        this.orders = [];
        this.createdAt = new Date().toISOString();
        this.updatedAt = new Date().toISOString();
        this.deleted = false;
        this.version = 1;
        this.syncStatus = 'synced';
    }

    createEmptyMeasurements() {
        const measurements = {};
        AppConfig.MEASUREMENT_FIELDS.forEach(field => {
            measurements[field] = '';
        });
        return measurements;
    }

    validate() {
        const errors = [];
        
        if (!this.name || this.name.trim().length < 2) {
            errors.push('نام مشتری باید حداقل ۲ کاراکتر باشد');
        }
        
        if (!this.phone || this.phone.trim().length < 10 || !/^\d+$/.test(this.phone)) {
            errors.push('شماره تلفن باید حداقل ۱۰ رقم عددی باشد');
        }
        
        AppConfig.MEASUREMENT_FIELDS.forEach(field => {
            const value = this.measurements[field];
            if (value && isNaN(parseFloat(value))) {
                errors.push(`فیلد ${field} باید عددی باشد`);
            }
        });
        
        if (this.sewingPriceAfghani && isNaN(parseInt(this.sewingPriceAfghani))) {
            errors.push('قیمت باید عددی باشد');
        }
        
        return errors;
    }

    toObject() {
        return {
            id: this.id,
            name: this.name,
            phone: this.phone,
            notes: this.notes,
            measurements: this.measurements,
            models: this.models,
            sewingPriceAfghani: this.sewingPriceAfghani,
            deliveryDay: this.deliveryDay,
            paymentReceived: this.paymentReceived,
            paymentDate: this.paymentDate,
            orders: this.orders,
            createdAt: this.createdAt,
            updatedAt: this.updatedAt,
            deleted: this.deleted,
            version: this.version,
            syncStatus: this.syncStatus
        };
    }

    static fromObject(obj) {
        if (!obj || typeof obj !== 'object') {
            return new Customer('', '');
        }
        
        const customer = new Customer(obj.name || '', obj.phone || '');
        
        // Copy all properties except name and phone
        Object.keys(obj).forEach(key => {
            if (key !== 'name' && key !== 'phone') {
                try {
                    customer[key] = obj[key];
                } catch (e) {
                    console.warn(`Failed to copy property ${key}:`, e);
                }
            }
        });
        
        // Ensure arrays are properly initialized
        if (!Array.isArray(customer.orders)) customer.orders = [];
        if (!customer.models) customer.models = { yakhun: "", sleeve: "", skirt: [], features: [] };
        if (!Array.isArray(customer.models.skirt)) customer.models.skirt = [];
        if (!Array.isArray(customer.models.features)) customer.models.features = [];
        if (!customer.measurements) customer.measurements = customer.createEmptyMeasurements();
        
        // Convert measurement values to numbers
        AppConfig.MEASUREMENT_FIELDS.forEach(field => {
            if (customer.measurements[field] && typeof customer.measurements[field] === 'string') {
                const numValue = parseFloat(customer.measurements[field]);
                if (!isNaN(numValue)) {
                    customer.measurements[field] = numValue;
                }
            }
        });
        
        // Convert price to number
        if (customer.sewingPriceAfghani && typeof customer.sewingPriceAfghani === 'string') {
            const priceValue = parseInt(customer.sewingPriceAfghani);
            if (!isNaN(priceValue)) {
                customer.sewingPriceAfghani = priceValue;
            }
        }
        
        return customer;
    }

    getFullName() {
        return this.name || 'بدون نام';
    }

    getFormattedPrice() {
        if (!this.sewingPriceAfghani) return 'تعیین نشده';
        return new Intl.NumberFormat('fa-IR').format(this.sewingPriceAfghani) + ' افغانی';
    }

    getDeliveryInfo() {
        if (!this.deliveryDay) return 'تعیین نشده';
        return this.deliveryDay;
    }

    hasMeasurement(field) {
        return this.measurements[field] && this.measurements[field] !== '';
    }

    getMeasurementValue(field) {
        return this.measurements[field] || '';
    }
}